name: 'insurance_etl'
version: '1.0.0'
config-version: 2

profile: 'insurance_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  insurance_etl:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  insurance_etl:
    +schema: staging
