version: 3

models:
  - name: dim_customer
    description: "Customer dimension containing customer details"
    columns:
      - name: customer_sk
        description: "Surrogate key for the customer"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Natural key for the customer"
        tests:
          - not_null
          - unique

  - name: dim_policy
    description: "Policy dimension with insurance policy details"
    columns:
      - name: policy_id
        description: "Business natural key for policy"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Business FK to customer"
      - name: status
        description: "Policy status (Active, Expired, Cancelled)"
        tests:
          - accepted_values:
              arguments:
                values: ['Active', 'Expired', 'Cancelled']
      - name: premium_amount
        description: "Premium amount for the policy"  
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "premium_amount >= 0"

  - name: fact_claim
    description: "Claims fact table linking customers, policies, and dates"
    columns:
      - name: claim_fact_id
        description: "Surrogate key for the claim fact"
        tests:
          - not_null
          - unique
      - name: claim_id
        description: "Business natural key for claim"
        tests:
          - not_null
          - unique
      - name: policy_sk
        description: "FK to dim_policy"
        tests:
          - relationships:
              arguments:
                to: ref('dim_policy')
                field: policy_sk
      - name: customer_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_sk
      - name: total_claim_amount
        description: "Total amount claimed"
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "total_claim_amount >= 0"
